### ISSUE TITLE
BarcodeReader not rendering

### ISSUE THREAD

**Issue by churrinfunflais** [kybarg/react-barcode-reader#1]
I'm having problem showing the camera with the example code, does it need something else, bellow the code. also the demo is no working...

```
import React, {Component} from 'react'
import BarcodeReader from 'react-barcode-reader'

class Barcode extends Component {
  constructor(props) {
    super(props);
    this.state = {
      result: 'No result',
    };
    this.handleScan = this.handleScan.bind(this);
  }

  handleScan(data) {
    this.setState({
      result: data,
    })
  }

  handleError(err) {
    console.error(err)
  }

  render() {
    return (
      <div>
        <BarcodeReader
          onError={this.handleError}
          onScan={this.handleScan}
        />
        <p>{this.state.result}</p>
      </div>
    )
  }
}

export default Barcode;
```

**Comment by mschmid** [comment]
Hi, i just gave it a try. This library only seems to recognize key presses, it does not read or render any camera image or visual barcode.
If you just type very fast on your keyboard while running the demo you can see what it does.

**Comment by raul-madrigal** [comment]
I tried this but it doesn't open the camera.

**Comment by kybarg** [comment]
@churrinfunflais this library is purposed for 2D QR readers only, If you want to read camera output use, https://github.com/kybarg/react-qr-scanner or similar library
