### ISSUE TITLE
Does it work with mobile camera as reading barcode image ?

### ISSUE THREAD

**Issue by satishminidukan** [kybarg/react-barcode-reader#2]
i tried it this library to scan barcode from camera , but it seems not working, not sure does it work with camera or not with mobile phone or it needs external reader/scanner device to provide data. please help to answer does this library work with mobile phone camera as barcode read or not

**Comment by SchenkDev** [comment]
Here is how barcode scanners work: it will scan the barcode image and translate that to a string, then this string is registered as a keyboard input and an enter key will be followed after.

This library is made to work with such keyboard inputs. A mobile phone camera does not have the function of a barcode scanner unless you are using an app that programs it to act like a barcode scanner, and thus providing that keyboard input. Hopefully I explained this clearly.

**Comment by kybarg** [comment]
@satishminidukan this library doesn't work with camera.
https://github.com/kybarg/react-barcode-reader/issues/1#issuecomment-609008550

**Comment by DHRUVDAVDA** [comment]
@satishminidukan you can try this 
https://www.npmjs.com/package/react-native-qrcode-scanner
