### ISSUE TITLE
Module for TypeScript

### ISSUE THREAD

**Issue by andresramirez82** [kybarg/react-barcode-reader#24]
module declaration for react-barcode-reader is missing. To be able to use in TYPESCRIPT

**Comment by Blueguy0301** [comment]
Hi, does this still works? if it still works, There seems to be an error in my code. The error was : 
` 'declare' modifier cannot be used in an already ambient context.` I am using vite-typescript and I also don't know where to put the types.d.ts file. I tried creating a folder in /node_modules/@types and adding the types.d.ts  (I named it the same name the same as the package).

**Comment by Blueguy0301** [comment]
Hi, I would like to ask if this still works on vite ? Right now, I have an error saying : 
`[vite] Internal server error: Failed to resolve entry for package "react-barcode-reader". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "react-barcode-reader". The package may have incorrect main/module/exports specified in its package.json.`

**Comment by jakekugel** [comment]
Thanks for writing it up.  A minor edit to the above.  The onError prop is a function with two arguments.  The above line:

`    onError?: (barcode: string) => void;
`

should be:

`    onError?: (barcode: string, message: string) => void;
`

**Comment by andresramirez82** [comment]
@dstotz thanks for the request
