### ISSUE TITLE
Gives Security Error on Hosting

### ISSUE THREAD

**Issue by osamaeshtiaq** [kybarg/react-barcode-reader#4]
When I am deploying the app on heroku and Calling my React Client URL this show a Security Error:
Blocked a frame with origin "https://2f5bd16b.ngrok.io" from accessing a cross-origin frame.

This Error Occurs in SHOPIFY

`←→1 of 2 errors on the page
SecurityError: Blocked a frame with origin "https://662bdced.ngrok.io" from accessing a cross-origin frame.
▶ 18 stack frames were collapsed.
Module../src/index.js
src/index.js:7
   4 | import App from './App';
   5 | import * as serviceWorker from './serviceWorker';
   6 | 
>  7 | ReactDOM.render(<App />, document.getElementById('root'));
   8 | 
   9 | // If you want your app to work offline and load faster, you can change
  10 | // unregister() to register() below. Note this comes with some pitfalls.
View compiled
__webpack_require__
/home/osama/Documents/dev/scanandship/scan-and-ship/webpack/bootstrap:785
  782 | };
  783 | 
  784 | // Execute the module function
> 785 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  786 | 
  787 | // Flag the module as loaded
  788 | module.l = true;
View compiled
fn
/home/osama/Documents/dev/scanandship/scan-and-ship/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
0
https://662bdced.ngrok.io/static/js/main.chunk.js:2545:18
__webpack_require__
/home/osama/Documents/dev/scanandship/scan-and-ship/webpack/bootstrap:785
  782 | };
  783 | 
  784 | // Execute the module function
> 785 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  786 | 
  787 | // Flag the module as loaded
  788 | module.l = true;
View compiled
checkDeferredModules
/home/osama/Documents/dev/scanandship/scan-and-ship/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 
View compiled
Array.webpackJsonpCallback [as push]
/home/osama/Documents/dev/scanandship/scan-and-ship/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
https://662bdced.ngrok.io/static/js/main.chunk.js:1:79`

**Comment by kybarg** [comment]
@osamaeshtiaq updated dependencies, should be fixed now. In any case this was relevant to development dependencies. Module code only has `React` as dependency
